### ISSUE TITLE
Button to link to template library

### ISSUE THREAD

**Issue by 4katie** [accordproject/template-studio#120]
Feature request - Although there is a search box to look at the list of templates available, it would be nice to have a button that links to https://templates.accordproject.org/ (to see full list of templates and explanations).

**Comment by rasfa98** [comment]
@irmerk I can fix this! 🙂

**Comment by jeromesimeon** [comment]
@irmerk I'm unsure if this is useful as well (per your PR comment), also it would help to have some design input and snapshot of what this looks like.

With Template Studio v2 being where most of the development work is happening, should we rather focus that question there anyway?

**Comment by rasfa98** [comment]
@irmerk @jeromesimeon Sorry for the late reply, I do not have as much time as i hoped for so I think it would be best to close my PR and let someone else take it.

**Comment by PseudoNerd** [comment]
Can we not add the link as a list item in the new template dropdown ?

**Comment by irmerk** [comment]
@4katie and @michael-grover any input?

**Comment by jeromesimeon** [comment]
I've used this:
<img width="556" alt="Screenshot 2019-10-25 at 10 44 46 AM" src="https://user-images.githubusercontent.com/670099/67580522-7a9c9700-f714-11e9-9fbc-cb294e0f8318.png">

<img width="730" alt="Screenshot 2019-10-25 at 10 44 36 AM" src="https://user-images.githubusercontent.com/670099/67580533-7d978780-f714-11e9-9b19-e9fa7f568893.png">

in the `0.20` branch. What do you guys think?

https://js-release-0-20--template-studio.netlify.com

**Comment by jeromesimeon** [comment]
> Can we not add the link as a list item in the new template dropdown ?

the template library feels like it belong more than the search bar, rather than "new template" ? maybe @Michael-Grover can suggest something there?

**Comment by Michael-Grover** [comment]
This tooltip looks like a dropdown menu. If we go this direction, let's make it center aligned so it looks more like a tooltip description and not a dropdown.

I think this link should open the template library in a new tab, because if a user clicks on this button without knowing what it does, they risk losing everything they wrote in the template editor.

Do you think this would belong in the help dropdown in TSV2? 
Is there room to just write "template library" in the nav bar instead of using an icon?

**Comment by PseudoNerd** [comment]
I thought that having the template library in the new template dropdown will help the user to navigate to the template library page while looking for new templates.

**Comment by Michael-Grover** [comment]
@jeromesimeon I think that looks really good

**Comment by jeromesimeon** [comment]
@4katie Does it look good enough, would this solution address your question/concern?

**Comment by 4katie** [comment]
Yes! Even the icons are perfect :)

**Comment by jeromesimeon** [comment]
Great! Thanks @4katie I'm closing this issue as resolved.
