### ISSUE TITLE
Upload of template archive

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/template-studio#32]
Upload of template archive files would allow for 'roundtripping' of templates. For example, a lawyer could create the grammar and model, download the template and share it with their engineer, the engineer uploads the template and adds the Ergo logic etc.

**Comment by Ro5s** [comment]
This 'roundtrip' feature seems pretty helpful for lawyers (like myself) who are still learning things on the Ergo side / are unsure on upload specifics.

**Comment by jeromesimeon** [comment]
Some initial support is in PR #39 #40

**Comment by jeromesimeon** [comment]
Still needs to work on properly reporting errors during upload/loading a template

**Comment by jeromesimeon** [comment]
Error reporting covered by new issue #42 
Closing this issue
