### ISSUE TITLE
Add git like changes for viewing non-standard contracts

### ISSUE THREAD

**Issue by TheLaughableCoder** [accordproject/template-studio#51]
It would be helpful for anyone reviewing a contract to see what changes have been made, Like git differences.

This would be especially handy if this is a standard contract that everyone in the idustry used. It would be easy to spot the differences between current contract and the one in the github repository. 

![image](https://user-images.githubusercontent.com/8724460/47850261-9aee8a00-de0f-11e8-959a-96077af4d0c8.png)

**Comment by jeromesimeon** [comment]
Monaco supports out of the box diff, apparently: https://microsoft.github.io/monaco-editor/

So maybe if we resolve #16 we get diff _for free_!

**Comment by jeromesimeon** [comment]
@TheLaughableCoder We are moving toward a new code-base at https://github.com/accordproject/template-studio-v2

Would you mind reopening the issue there and closing this one? Would be much appreciated!

**Comment by jeromesimeon** [comment]
This issue has been moved to https://github.com/accordproject/template-studio-v2/issues/9
