### ISSUE TITLE
Large contract text crashes the browser

### ISSUE THREAD

**Issue by RyanHow** [accordproject/template-studio#54]
If you load some contract text that is not much longer than a 100 lines. Then the browser hangs and crashes.

**Comment by jeromesimeon** [comment]
Thanks for the report. I could replicate the issue (on Chrome/MacOs X). Could you please let us know which platform/browser you are using?

**Comment by RyanHow** [comment]
Windows Chrome

Firefox on Windows seems a bit more forgiving, but it hangs a lot and because almost unusable after 100 lines.

The issue appeared to be around the template.buildGrammar() call

**Comment by jeromesimeon** [comment]
Yes, I just traced it there as well. This is the call building the internal grammar for the template. I've filed an issue against Cicero here:

https://github.com/accordproject/cicero/issues/232

So far, the system has been used mostly for single clause templates (possibly placed inside larger contracts) so we'll have to investigate.

**Comment by RyanHow** [comment]
Thank you

**Comment by jeromesimeon** [comment]
Note that I've had slightly better luck with shorter lines. In case that is a useful workaround until we fix this issue: 
<img width="1041" alt="screen shot 2018-11-07 at 10 44 08 am" src="https://user-images.githubusercontent.com/670099/48142123-29349700-e27a-11e8-8cd4-4f5bf9bd53f2.png">

**Comment by jeromesimeon** [comment]
This might provide some useful hints (i.e., tokenizer) https://github.com/kach/nearley/issues/111

**Comment by jeromesimeon** [comment]
This problem can be traced to performance issues when using large strings in the Nearley parser used in Cicero. A PR to fix the problem (by upgrading to a more recent version of Nearley) is pending review here https://github.com/accordproject/cicero/pull/233

Once that PR is merged and a new version of Cicero is published, the template studio should work for much larger contract text.

**Comment by jeromesimeon** [comment]
The issue also happen for form feed:
```
bash-3.2$ npm install -g nearley@2.15.1 
+ nearley@2.15.1
added 10 packages from 9 contributors in 1.302s
bash-3.2$ nearleyc teststring.ne -o teststring.js  
undefined:1
"a	b"
  ^

SyntaxError: Unexpected token  in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.value (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley-language-bootstrapped.js:30:26)
    at Lexer.next (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/node_modules/moo/moo.js:377:34)
    at Parser.feed (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley.js:270:30)
    at StreamWrapper.write [as _write] (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
bash-3.2$ npm install -g nearley@2.13.0
+ nearley@2.13.0
removed 1 package and updated 1 package in 0.676s
bash-3.2$ nearleyc teststring.ne -o teststring.js
```

**Comment by RyanHow** [comment]
@jeromesimeon This seems to be working magnitudes better now. Thanks!
