### ISSUE TITLE
Download link for individual files in the Test Execution panel

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/template-studio#67]
When using a template archive locally (for example with `cicero execute`), I may want to seed/reuse the JSON and Text values from Template Studio.

We could make this easier by adding a download button (or link) to each of the fields in the Test Execution panel. It would also be helpful to be able to download the `sample.txt` and `grammar.tem` individually too.

**Comment by jeromesimeon** [comment]
I would suggest tests should become part of the archive, so when you download them you get the corresponding tests.

**Comment by jeromesimeon** [comment]
This issue has been moved to https://github.com/accordproject/template-studio-v2/issues/8
