### ISSUE TITLE
Add new models and new logic files

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/template-studio#83]
Currently, the number of models and logic files is fixed based on the loaded templates. It would be good to be able to add new empty model or logic files.

**Comment by jeromesimeon** [comment]
This could be with a small `+` button on the right to the model/logic tabs here:
<img width="694" alt="screen shot 2019-01-15 at 1 48 14 pm" src="https://user-images.githubusercontent.com/670099/51202291-6b0e3900-18cc-11e9-8f2b-089ff168a02d.png">

**Comment by jeromesimeon** [comment]
If we can add new model or logic file, we might want to also be able to remove some.

**Comment by Michael-Grover-C** [comment]
Potential solution mockup:

https://invis.io/GNQDQ9HZ5QE#/345313118_no_Template

**Comment by jeromesimeon** [comment]
Let's use the great mockup from @Michael-Grover-C  at https://invis.io/GNQDQ9HZ5QE#/345313118_no_Template

**Comment by jeromesimeon** [comment]
This issue has been moved to https://github.com/accordproject/cicero-ui/issues/8
