### ISSUE TITLE
Rich Text Full Contract Editor

### ISSUE THREAD

**Issue by dselman** [accordproject/template-studio#90]
Provide a rich text editor that allows the user to embed clause templates.

**Comment by Michael-Grover-C** [comment]
<img width="972" alt="smart contract template editor" src="https://user-images.githubusercontent.com/40569793/52804653-bc882000-3052-11e9-9113-ac4f8f8c39df.png">

This is a preview of a wireframe I'm working on for a full contract editor within the template studio. I'm going to post a higher fidelity digital version soon.

**Comment by jeromesimeon** [comment]
We should use the rich text editor published at https://www.npmjs.com/package/@accordproject/markdown-editor

**Comment by jeromesimeon** [comment]
This issue has been moved to: https://github.com/accordproject/react-components/issues/6
