### ISSUE TITLE
Open in template studio not working

### ISSUE THREAD

**Issue by contractpendev** [accordproject/template-studio#95]
From this page click Open in template studio
"Could not load template, The template targets Cicero (^0.11.1) but the Cicero version is 0.10.2."
https://templates.accordproject.org/helloworldstate@0.10.0.html

Same for most other templates I assume
https://templates.accordproject.org/

**Comment by dselman** [comment]
Yes, we need to update template studio to use Cicero v0.11. You should still be able to open the older versions of the templates.

**Comment by dselman** [comment]
Working on this now.

**Comment by contractpendev** [comment]
Hello, not working https://templates.accordproject.org/supplyagreement@0.9.0.html - would be nice to be working before Saturday so if people click at event they can view it in template studio.

**Comment by dselman** [comment]
You can still open the prior versions of the templates - use the Versions drop down. Alternatively you can open compatible versions from with studio itself.

**Comment by jeromesimeon** [comment]
@contractpendev Template Studio is still running Cicero 0.10, which shows most of the same templates.

**Comment by jeromesimeon** [comment]
A branch of template studio which works (not thoroughly tested) on the current development version of Cicero is here https://github.com/accordproject/template-studio/tree/cicero-0.11

**Comment by jeromesimeon** [comment]
@contractpendev the "open in studio" button from the latest version of each templates should be working again. Can you please confirm?

**Comment by jeromesimeon** [comment]
This should now be resolved. Please re-open if any issue.
