### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by dselman** [accordproject/template-studio#99]
We modularize Template Studio into a set of discrete React components, which interact via [Redux](http://redux.js.org).

## Ergo (Logic) Editor
- Based on https://github.com/react-monaco-editor/react-monaco-editor
- We should refactor the VSCode plugin to share the same Language Server and use it with the Monaco editor. https://github.com/TypeFox/monaco-languageclient
- https://langserver.org
- Existing LSP: https://github.com/accordproject/ergo-vscode-plugin/blob/master/server/src/server.ts

## Concerto (Model) Text Editor
- Build a new LSP implementation for Concerto, based on https://github.com/hyperledger/composer-vscode-plugin/blob/master/server/src/server.ts
- Use Monaco to edit CTO files

## Concerto (Model) Graphical Editor
- Viewer/editor for Concerto models as interactive UML style diagram, using https://github.com/projectstorm/react-diagrams

## Concerto (Model) Form-based Editor
- Viewer/editor for Concerto models as a set of class declarations, with properties specified using actions and forms (Add Concept, Add Transaction etc).

## Template Library Component
- https://github.com/accordproject/react-components
- Configurable component to view the contents of an AP format template library

## Clause Plugin
- A plugin for the contract editor that knows how to both Edit and Design AP Clauses https://github.com/accordproject/contract-editor/blob/master/src/plugins/clausePlugin.js
- In Edit mode only variable values can be supplied
- In Design mode the grammar text can be edited, variables inserted and their types specified

## Contract Editor (extends markdown-editor)
- https://github.com/accordproject/contract-editor
- In Edit mode can supply values for variables and edit the text of the contract
- In Design mode new variables can be inserted and can drag-drop Clauses into the contract

## Concerto Form Component
- Generate a web form to edit an instance of a Concerto model
- https://www.npmjs.com/package/concerto-form-react
- Use to edit `request.json` to test a contract
- Use to visualise `response.json` and `state.json`

## Package.json Editor
- Based on Monaco JSON file support

## README.md Editor
- Based on `markdown-editor`

**Comment by jeromesimeon** [comment]
This issue has been moved to https://github.com/accordproject/template-studio-v2/issues/1
